### ISSUE TITLE
Feature Request :- Can we have feature in toolbar to change the repeating time interval?

### ISSUE THREAD

**Issue by bharatbl94** [ayushchd/cowin_js_bot#10]
Now Cowin APIs have made count limit over public APIs. With just 25-30 calls it gives a "Something went wrong error" I have checked it happened due to CORS error.
Manually change the interval may solve this issue.

**Comment by adbrew** [comment]
Coming up in next release. Should be about 24-48 hours.

**Comment by ayushchd** [comment]
Coming up in next release - should be in about 24-48 hours.

**Comment by ayushchd** [comment]
Live now
