### ISSUE TITLE
Showing Error

### ISSUE THREAD

**Issue by vireshb01** [ayushchd/cowin_js_bot#11]
Afte running for 2 mins it starts showing error

**Comment by vireshb01** [comment]
> Afte running for 2 mins it starts showing error  'Something went wrong. Please try again!'

**Comment by AtomsX1** [comment]
Yes , the same error is popping up for me too

**Comment by ayushchd** [comment]
Duplicate https://github.com/ayushchd/cowin_js_bot/issues/10
