### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by darkQuanger** [ayushchd/cowin_js_bot#2]
Its showing error to get the XML file. Have you removed the file?

**Comment by ayushchd** [comment]
I think there was an issue with the S3 permissions. Check now?

**Comment by Aditya378** [comment]
> I think there was an issue with the S3 permissions. Check now?

Yes, it's working now, previously it was giving 403 Error before.

net::ERR_ABORTED 403 (Forbidden)

**Comment by darkQuanger** [comment]
yes, its live again. thanks.
