### ISSUE TITLE
Can't change the time interval in extension.

### ISSUE THREAD

**Issue by darkQuanger** [ayushchd/cowin_js_bot#5]
Happy to see, you converted the code into chrome extension but it would be helpful if you also retain the access for previous code.

**Comment by ayushchd** [comment]
It would be fairly time-consuming for me to maintain 2 versions of this. 

I purposely removed the time interval because I wanted to reduce decision making on part of users, and felt that the default value pretty much works for all use-cases.

Could you help me understand what's your thought process behind wanting to customize the time interval?

**Comment by darkQuanger** [comment]
I felt the extention is little bit buggy than the script. Script was running fine for me, was able to book one slot (thanks to you). In the script I set the value for the whole script repeating to 1 sec, and my search was confined to just particular one district. It was working so fast that it booked before getting notification in some telegram group.

The big issue i've felt that in the case of extention, I am not understanding if I am still logged in or not  and also the number of runs is not updating.

**Comment by ayushchd** [comment]
The extension is pretty much using the exact same script with added features. It waits for 500ms between searches, and 0s between runs.

The number of runs should be updating in real time, can you try updating the extension?

Also, logged in/logged out behavior would be the exact same with script or extension.

**Comment by darkQuanger** [comment]
Its working now. Thanks.

**Comment by Tnu02** [comment]
Hey, thanks for the script as well as the addon.. It works great..
Just a suggestion, is it possible to include any kind of timer of 15 mins ago that we could know about the session start and end time..!!

**Comment by ayushchd** [comment]
Can you explain more? Timer for what exactly - since login or since you run the search?

**Comment by Tnu02** [comment]
Timer in a way that we get any kind of notification or something for session expiration.. Like 15 min count down..

**Comment by darkQuanger** [comment]
The extention is not working now, after 25-30 runs the portal is showing 'something went wrong, please try again'.

**Comment by bharatbl94** [comment]
> The extension is not working now, after 25-30 runs the portal is showing 'something went wrong, please try again'.

I am also facing the same.

**Comment by ayushchd** [comment]
CoWIN is now throttling IPs temporarily if you trigger too many requests. keep no. of runs/searches low to avoid seeing that error. Support for customizing time interval coming up in next update.
